### ISSUE TITLE
Fix failing test cases

### ISSUE THREAD

**Issue by etosch** [plasma-umass/parcel#5]
- [x] crossWorksheetRangeExtraction
- [x] multipleRangeExtraction
- [x] testHLOOKUP

**Comment by etosch** [comment]
Note: at least `crossWorksheetRangeExtraction` fails due to parsing ambiguity for the case

   =foo(A1:A2,false)

It tries to parse `A1:A2,false` as a range, but never backtracks to the point where it separates A1:A2 and false into different arguments.

**Comment by dbarowy** [comment]
These are all fixed.
